### ISSUE TITLE
fielddata question

### ISSUE THREAD

**Issue by mfyang** [elastic/elasticsearch-definitive-guide#348]
On page 121 of the printed version,  there is a line 

```
"when sorting, we need to map a document to its terms. In other words, we need to 'uninvert' the inverted index. 
```

I don't quite understand this sentence.  What does it mean by 'map a document to its terms'? and why sorting need this?

**Comment by polyfractal** [comment]
Basically, in a sorting context we need to ask *"what value does this document have?"*, so that we can compare against other documents and arrange a sorted order.  Which means the data structure needs to support a `DocID -> Value` relationship

This is different from searching, where a search asks *"what documents have this term?"*.  This is an opposite data structure which supports a `Value -> DocIDs` lookup.

If you look at the [end of the Aggregations chapter](http://www.elastic.co/guide/en/elasticsearch/guide/master/fielddata.html), you'll see a longer, more technical explanation of how inverted indices are related to field data.

Does that help?
