### ISSUE TITLE
Breaking changes in elasticsearch 2.0 - the way to update?

### ISSUE THREAD

**Issue by codesurf42** [elastic/elasticsearch-definitive-guide#435]
There are some breaking changes in Es 2.0, like installing marvel or tokenizers (I am just learning Es but I already found it quite annoying that many examples do not work and there is no simple answer "how to do it in 2.0"). 
What is a strategy for this book to keep up to date with new version? I think examples for both should be just fine...?

**Comment by aliteralmind** [comment]
Regarding [installing Marvel](https://github.com/elastic/elasticsearch-definitive-guide/blob/3f0fb1452bc946055f541ae08544c3c557047994/010_Intro/10_Installing_ES.asciidoc), this is now incorrect:

   ./bin/plugin -i elasticsearch/marvel/latest

It's been a couple days, but I believe this is now correct:

    ./bin/plugin install elasticsearch/marvel/latest

**Comment by polyfractal** [comment]
Good question, we've been talking a lot internally about how we want to attack it.

We'll likely create a new `2.0` branch and start working through the various changes (breaking and otherwise).  Then we'll have a versioned book just like our regular docs, and default the "current" to `2.0` once it is done.

Thanks for your patience while we sort this out! :)

**Comment by polyfractal** [comment]
Just as a quick update, we branched the 1.x off, so now master is tracking 2.0+.  The "current" version of the Guide (e.g. http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/) compiles from master, so that'll be receiving the updates as we work on them.

If you want to follow progress of various things, just watch the commit log for master from now on :)

**Comment by danielmitterdorfer** [comment]
@polyfractal: Should we close this one as duplicate and track it in #659?

**Comment by polyfractal** [comment]
++  Let's track in #659
