### ISSUE TITLE
How can I download this as a PDF

### ISSUE THREAD

**Issue by jononomo** [elastic/elasticsearch-definitive-guide#538]
I need to download this guide as a PDF so I can easily read it offline - how can I do this?

Thanks!

**Comment by markwalkom** [comment]
We don't provide this as a PDF sorry.

You can get the guide from O'Rielly's though - http://shop.oreilly.com/product/0636920028505.do

**Comment by polyfractal** [comment]
Some folks had (some) luck compiling to PDF via asciidoctor in this thread: #421

You could also just compile the book to HTML and read that offline.  Not quite as convenient as a PDF, but all the tooling is ready to go (since that's how we generate our docs).  You can use our [Docs Generator](https://github.com/elastic/docs) tool, which should be pretty plug'n'play if you have perl on your machine.

You could even tell the generator to spit out one giant HTML page by not chunking, then print that to PDF.  Still not quite as friendly (e.g. links wouldn't work, I don't think), but an option.

**Comment by jononomo** [comment]
@markwalkom why don't you provide this as a PDF?

**Comment by polyfractal** [comment]
Truthfully, it's just a time/prioritization issue.  It takes a lot of work keeping the Guide up-to-date with Elasticsearch (which is a very fast moving piece of software), and Clint and myself both have other responsibilities outside the book.  

Fixing the various encoding issues that prevent clean PDF generation, modifying the build process to generate PDFs, etc would entail a fair amount of work.  We'd certainly *like* to provide a PDF (and mobi and epub and all the other formats), but realistically it just isn't a priority at the moment.

Sorry :(
